// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nvhnbxmctiopmlyfzjqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52aG5ieG1jdGlvcG1seWZ6anF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU2MTcyNDAsImV4cCI6MjEwMTE5MzI0MH0.qvqTQuEcSQ0MvzunHGbIvj8i6j6rRdLna2yNtfelnM0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});